services:

  api:
    build: ./smartboodschappenlijstje-api
    container_name: smart-api
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./smartboodschappenlijstje-frontend
    container_name: smart-frontend
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - api
      - db

  db:
    image: mysql:8.0
    container_name: smart-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: smart_groceries
      MYSQL_USER: groceries_user
      MYSQL_PASSWORD: groceries_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: smart-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data:
